services:
  nginx_main:
    image: nginx:latest
    container_name: nginx_main
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginxContainer/website:/usr/share/nginx/html
      - ./nginxContainer/nginxConf/php.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main_intranet

  php:
    image: php:fpm-alpine
    container_name: php_main
    volumes:
      - ./nginxContainer/website:/usr/share/nginx/html
    networks:
      - main_intranet
networks:
  main_intranet:
    driver: bridge
