services:
  nginx_main:
    image: nginx:latest
    container_name: nginx_main
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginxContainer/website:/usr/share/nginx/html
      - ./nginxContainer/certs:/etc/nginx/ssl
      - ./nginxContainer/nginxConf/php.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_main
    networks:
      - main_intranet
      - client_intranet

  php_main:
    build: ./php-fpmConf/
    container_name: php_main
    restart: always
    env_file:
      - "./mysqlContainer/mysqlConf/mysql.env"
    volumes:
      - ./nginxContainer/website:/usr/share/nginx/html
      - ../template/testNginx:/clients
    command: sh -c "chown -R www-data:www-data /usr/share/nginx/html /clients && chmod -R 755 /usr/share/nginx/html /clients && php-fpm"
    networks:
      - main_intranet

  mysql_main:
    image: mysql:latest
    container_name: mysql_main
    restart: always
    env_file:
      - "./mysqlContainer/mysqlConf/mysql.env"
    volumes:
      - ./mysqlContainer/mysqlData:/var/lib/mysql
    networks:
      - main_intranet

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_main
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql_main
    env_file:
      - "./phpmyadminConf/phpmyadmin.env"
    networks:
      - main_intranet

  filemanager2:
    image: filebrowser/filebrowser
    restart: always
    volumes:
      - ./nginxContainer/website:/srv
      - ../template/testNginx:/srv/test
      - ../clients:/srv/clients
    networks:
      main_intranet:
        aliases:
          - files.egenerei.es

networks:
  main_intranet:
    driver: bridge
  client_intranet:
    driver: bridge
