---
- name: Automatic client Docker infrastructure deployment
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Copy docker-compose-watch.sh to server
      ansible.builtin.copy:
        src: ../autoDockerUp/docker-compose-watch.sh
        dest: /usr/local/bin/docker-compose-watch.sh
        owner: root
        group: root
        mode: '0755'

    - name: Copy docker-compose-watch.service to server
      ansible.builtin.copy:
        src: ../autoDockerUp/docker-compose-watch.service
        dest: /etc/systemd/system/docker-compose-watch.service
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start docker-compose-watch
      systemd:
        name: docker-compose-watch.service
        enabled: yes
        state: started