---
- name: Automatic client Docker infrastructure deployment
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Ensure docker-compose-watch.sh script is installed
      copy:
        dest: /usr/local/bin/docker-compose-watch.sh
        owner: root
        group: root
        mode: '0755'
        content: |
          #!/bin/bash

          WATCH_DIR="/docker/clients"
          LOG_FILE="/docker/inotify-docker.log"
          MAX_RETRIES=6     # Retry for 1 minute (6 x 10s)
          SLEEP_INTERVAL=10

          inotifywait -m -e create --format "%f" "$WATCH_DIR" | while read NEW_ENTRY; do
              NEW_PATH="$WATCH_DIR/$NEW_ENTRY"

              # Only proceed if it's a directory
              if [ -d "$NEW_PATH" ]; then
                  echo "$(date) - Detected new directory: $NEW_PATH" >> "$LOG_FILE"

                  ATTEMPT=1
                  while [ $ATTEMPT -le $MAX_RETRIES ]; do
                      if [ -f "$NEW_PATH/compose.yaml" ] || [ -f "$NEW_PATH/docker-compose.yml" ]; then
                          echo "$(date) - Found compose file in $NEW_PATH (attempt $ATTEMPT)" >> "$LOG_FILE"
                          (
                              cd "$NEW_PATH"
                              docker compose up -d >> "$LOG_FILE" 2>&1
                          )
                          break
                      else
                          echo "$(date) - Compose file not found in $NEW_PATH (attempt $ATTEMPT)" >> "$LOG_FILE"
                          sleep "$SLEEP_INTERVAL"
                          ((ATTEMPT++))
                      fi
                  done

                  if [ $ATTEMPT -gt $MAX_RETRIES ]; then
                      echo "$(date) - Failed to find compose file in $NEW_PATH after $MAX_RETRIES attempts" >> "$LOG_FILE"
                  fi
              fi
          done

    - name: Install compose-watcher systemd service
      copy:
        dest: /etc/systemd/system/docker-compose-watch.service
        owner: root
        group: root
        mode: '0644'
        content: |
          [Unit]
          Description=Inotify Docker Compose Watcher
          After=network.target docker.service
          Requires=docker.service

          [Service]
          ExecStart=/usr/local/bin/docker-compose-watch.sh
          Restart=always
          RestartSec=5
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start compose-watcher
      systemd:
        name: docker-compose-watch.service
        enabled: yes
        state: started