---
- name: Packages (Ubuntu 24 Jammy)
  hosts: all
  become: true
  tasks:
    - name: Ensure the timezone is set to Europe/Madrid
      ansible.builtin.timezone:
        name: Europe/Madrid

    - name: Remove conflicting Docker packages from Ubuntu repo
      apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: yes

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
        purge: yes

    - name: Install packages needed to add docker's repository
      apt:
        name:
          - software-properties-common
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install docker & docker-compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - inotify-tools
        state: present
        update_cache: yes
      notify:
        - Start and enable docker service

  handlers:
    - name: Start and enable docker service
      ansible.builtin.service:
        name: docker.service
        state: started
        enabled: yes